# Generated by Django 3.1.1 on 2021-06-10 03:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
import utils.generate_id


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testID', models.CharField(max_length=16, unique=True)),
                ('testTitle', models.CharField(max_length=1024)),
                ('testAuthor', models.CharField(max_length=1024)),
                ('testCode', models.CharField(default=None, max_length=6)),
                ('testSchedule', models.DateField()),
                ('timeLimit', models.IntegerField(default=0, null=True)),
                ('passwordAdminTest', models.CharField(default=None, max_length=16, null=True)),
                ('passwordTest', models.CharField(default='123456', max_length=16)),
                ('maxScore', models.IntegerField(default=0)),
                ('welcomeMessage', models.TextField()),
                ('settings', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='TestTaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testTakerID', models.CharField(max_length=16, unique=True)),
                ('session_code', models.CharField(max_length=16, unique=True)),
                ('session_password', models.CharField(max_length=16)),
                ('testTakerName', models.CharField(max_length=128)),
                ('testTakerGroup', models.CharField(blank=True, max_length=128, null=True)),
                ('scoreObtained', models.IntegerField(default=0)),
                ('lastAnswered', models.IntegerField(default=0)),
                ('timeStart', models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 10, 10, 22, 27, 972680), null=True)),
                ('timeFinish', models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 10, 10, 22, 27, 972711), null=True)),
                ('testPackage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.testpackage')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questID', models.CharField(max_length=16, unique=True)),
                ('questionNum', models.IntegerField(default=0)),
                ('question', models.TextField()),
                ('choices', models.JSONField()),
                ('answerKey', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('trueScore', models.FloatField(default=0)),
                ('defaultScore', models.FloatField(default=0)),
                ('falseScore', models.FloatField(default=0)),
                ('testPackage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.testpackage')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerID', models.CharField(default=utils.generate_id.generate_id, max_length=16)),
                ('session_code', models.CharField(max_length=16)),
                ('testID', models.CharField(max_length=16)),
                ('question', models.CharField(max_length=16)),
                ('answer', models.CharField(blank=True, max_length=4096, null=True)),
                ('isTrue', models.BooleanField(blank=True, default=None, null=True)),
                ('testTaker', models.ForeignKey(max_length=16, on_delete=django.db.models.deletion.CASCADE, to='Test.testtaker')),
            ],
        ),
    ]
