# Generated by Django 3.1.1 on 2020-12-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_auto_20201208_0551'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestWelcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testID', models.CharField(max_length=16)),
                ('welcomeMessage', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='testpackage',
            name='welcomeMessageID',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='questID',
            field=models.CharField(default='690727d2d763111c', max_length=16),
        ),
        migrations.AlterField(
            model_name='testpackage',
            name='testID',
            field=models.CharField(default='33f402116a95d9fb', max_length=16),
        ),
        migrations.AlterField(
            model_name='testtaker',
            name='testTakerID',
            field=models.CharField(default='366edddc33d49a94', max_length=16, unique=True),
        ),
    ]
