# Generated by Django 3.1.1 on 2020-12-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0005_auto_20201220_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questID',
            field=models.CharField(default='08ad5395c40f4cbd', max_length=16),
        ),
        migrations.AlterField(
            model_name='testpackage',
            name='testID',
            field=models.CharField(default='3a532827b0f16dc3', max_length=16),
        ),
        migrations.AlterField(
            model_name='testtaker',
            name='testTakerID',
            field=models.CharField(default='c501a451ec4fbf91', max_length=16),
        ),
    ]
