# Generated by Django 3.1.1 on 2020-12-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0006_auto_20201220_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chek',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='questID',
            field=models.CharField(default='eb38ee3243b0deed', max_length=16),
        ),
        migrations.AlterField(
            model_name='testpackage',
            name='testID',
            field=models.CharField(default='2d369a563dc36cd4', max_length=16),
        ),
        migrations.AlterField(
            model_name='testtaker',
            name='testTakerID',
            field=models.CharField(default='f3a6364dcc71f133', max_length=16),
        ),
    ]
