# Generated by Django 3.1.1 on 2021-06-10 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0006_auto_20210610_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='questionNum',
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testpackage',
            name='settings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testtaker',
            name='timeFinish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 10, 12, 59, 48, 79047), null=True),
        ),
        migrations.AlterField(
            model_name='testtaker',
            name='timeStart',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 10, 12, 59, 48, 79022), null=True),
        ),
    ]
