# Generated by Django 3.1.1 on 2021-06-10 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0007_auto_20210610_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpackage',
            name='testID',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='testtaker',
            name='timeFinish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 10, 13, 19, 20, 135834), null=True),
        ),
        migrations.AlterField(
            model_name='testtaker',
            name='timeStart',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 10, 13, 19, 20, 135801), null=True),
        ),
    ]
