# Generated by Django 3.1.1 on 2020-12-20 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0007_auto_20201220_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questID',
            field=models.CharField(default='8a0aca6220c6a5be', max_length=16),
        ),
        migrations.AlterField(
            model_name='testpackage',
            name='testID',
            field=models.CharField(default='f6b2aa01faedc5a8', max_length=16),
        ),
        migrations.AlterField(
            model_name='testtaker',
            name='testTakerID',
            field=models.CharField(default='288a0183a27d9d03', max_length=16),
        ),
    ]
