# Generated by Django 3.1.1 on 2020-12-20 03:34

import Test.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0009_auto_20201220_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtaker',
            name='timeStart',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 20, 10, 34, 28, 491061), null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answerID',
            field=models.CharField(default=Test.models.Answer.generate_id, max_length=16),
        ),
        migrations.AlterField(
            model_name='question',
            name='questID',
            field=models.CharField(default='f289adb097624298', max_length=16),
        ),
        migrations.AlterField(
            model_name='testpackage',
            name='testID',
            field=models.CharField(default='1ddb784c4f66c9df', max_length=16),
        ),
        migrations.AlterField(
            model_name='testtaker',
            name='testTakerID',
            field=models.CharField(default='166de6666c63607b', max_length=16),
        ),
    ]
