# Generated by Django 3.1.1 on 2021-06-11 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0009_auto_20210610_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testpackage',
            name='maxScore',
        ),
        migrations.AlterField(
            model_name='testtaker',
            name='timeFinish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 11, 19, 58, 47, 4822), null=True),
        ),
        migrations.AlterField(
            model_name='testtaker',
            name='timeStart',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 11, 19, 58, 47, 4611), null=True),
        ),
    ]
