# Generated by Django 3.1.1 on 2020-12-21 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0010_auto_20201220_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtaker',
            name='timeFinish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 21, 20, 35, 18, 884465), null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='questID',
            field=models.CharField(default='2c898796189d052c', max_length=16),
        ),
        migrations.AlterField(
            model_name='testpackage',
            name='testID',
            field=models.CharField(default='841191aa7a022083', max_length=16),
        ),
        migrations.AlterField(
            model_name='testtaker',
            name='testTakerID',
            field=models.CharField(default='d1d183735b4ab8da', max_length=16),
        ),
        migrations.AlterField(
            model_name='testtaker',
            name='timeStart',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 21, 20, 35, 18, 884437), null=True),
        ),
    ]
