# Generated by Django 3.1.1 on 2021-06-12 06:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0011_auto_20210612_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='session_code',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Test.question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='answerID',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='testTaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.testtaker'),
        ),
        migrations.AlterField(
            model_name='testtaker',
            name='timeFinish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 12, 13, 52, 7, 235586), null=True),
        ),
        migrations.AlterField(
            model_name='testtaker',
            name='timeStart',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 12, 13, 52, 7, 235558), null=True),
        ),
    ]
