# Generated by Django 3.1.1 on 2021-06-12 06:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0012_auto_20210612_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_question', to='Test.question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='testTaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_testTaker', to='Test.testtaker'),
        ),
        migrations.AlterField(
            model_name='testtaker',
            name='timeFinish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 12, 13, 58, 55, 843324), null=True),
        ),
        migrations.AlterField(
            model_name='testtaker',
            name='timeStart',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 12, 13, 58, 55, 843284), null=True),
        ),
    ]
