# Generated by Django 3.1.1 on 2021-01-04 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0013_auto_20210101_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questID',
            field=models.CharField(default='312e0427d87f21e8', max_length=16),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testpackage',
            name='testID',
            field=models.CharField(default='d3fde48f6f651c5d', max_length=16),
        ),
        migrations.AlterField(
            model_name='testtaker',
            name='testTakerID',
            field=models.CharField(default='2ba75c0716aa81e3', max_length=16),
        ),
        migrations.AlterField(
            model_name='testtaker',
            name='timeFinish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 4, 14, 24, 42, 806983), null=True),
        ),
        migrations.AlterField(
            model_name='testtaker',
            name='timeStart',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 4, 14, 24, 42, 806942), null=True),
        ),
    ]
