# Generated by Django 3.1.1 on 2021-06-08 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0014_auto_20210104_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questID',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='testpackage',
            name='testID',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='testtaker',
            name='testTakerID',
            field=models.CharField(default='4b052d8d152bfa74', max_length=16),
        ),
        migrations.AlterField(
            model_name='testtaker',
            name='timeFinish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 8, 14, 2, 33, 243695), null=True),
        ),
        migrations.AlterField(
            model_name='testtaker',
            name='timeStart',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 8, 14, 2, 33, 243655), null=True),
        ),
    ]
