# Generated by Django 3.1.1 on 2021-06-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0015_auto_20210614_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testpackage',
            name='testSchedule',
        ),
        migrations.AddField(
            model_name='testpackage',
            name='testScheduleFinish',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='testpackage',
            name='testScheduleOpen',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='testtaker',
            name='timeFinish',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testtaker',
            name='timeStart',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
