# Generated by Django 3.1.1 on 2021-07-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0019_auto_20210727_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpackage',
            name='welcomeMessage',
            field=models.TextField(null=True),
        ),
    ]
